[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"
authors = ["Raoul Luqué <raoulsluque@gmail.com>"]
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rustboy"
path = "src/main.rs"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.11"
log = "0.4"
wgpu = "24.0"

