name: Run Blarggs Test ROMs

on: [ push, pull_request ]

jobs:
  test_roms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rom:
          - "roms/test_roms/blarggs/cput_instrs/03-op sp,hl.gb"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-test-roms-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-roms-

      - name: Install xvfb for headless testing
        run: sudo apt-get install -y xvfb
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build
        run: RUST_BACKTRACE=1 RUST_LOG=debug cargo build

      - name: Run Test ROM
        run: |
          timeout 60s xvfb-run -a sh -c 'RUST_BACKTRACE=1 RUST_LOG=debug cargo run -- --DOCTOR --ROM "${{ matrix.rom }}" | tee output.log'
          cat output.log
          grep "Testing" output.log