name: Run Blarggs Test ROMs

on: [ push, pull_request ]

jobs:
  test_roms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rom:
          - "roms/test_roms/blarggs/cput_instrs/03-op sp,hl.gb"
          - "roms/test_roms/blarggs/cpu_instrs/07-jr,jp,call,ret,rst.gb"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-test-roms-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-roms-

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build
        run: RUST_BACKTRACE=1 RUST_LOG=debug cargo build

      - name: Run Test ROM
        run: |
          timeout 30s sh -c 'RUST_BACKTRACE=1 RUST_LOG=debug cargo run -- --HEADLESS --DOCTOR --ROM "${{ matrix.rom }}"' | tee output.log
          cat output.log
          grep "Write to SB: P
          Write to SB: a
          Write to SB: s
          Write to SB: s
          Write to SB: e
          Write to SB: d" output.log
